#!/usr/bin/env bash
# Baaton Setup — Interactive configuration for API access
#
# Creates a .baaton config file in the current directory
# Tests the connection and shows available projects

set -euo pipefail

echo "🎯 Baaton Setup"
echo "==============="
echo ""

# ─── API URL ──────────────────────────────────────────

read -rp "API URL [https://api.baaton.dev]: " API_URL
API_URL="${API_URL:-https://api.baaton.dev}"

# ─── API Key ──────────────────────────────────────────

echo ""
echo "Get your API key from: ${API_URL/api./} → Project Settings → API Keys"
read -rp "API Key (baa_...): " API_KEY

if [ -z "$API_KEY" ]; then
  echo "Error: API key is required" >&2
  exit 1
fi

if [[ ! "$API_KEY" == baa_* ]]; then
  echo "Warning: API key doesn't start with 'baa_' — are you sure it's correct?"
  read -rp "Continue anyway? [y/N]: " confirm
  [[ "$confirm" =~ ^[Yy] ]] || exit 1
fi

# ─── Test Connection ──────────────────────────────────

echo ""
echo "Testing connection..."

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
  "${API_URL}/api/v1/projects" \
  -H "Authorization: Bearer ${API_KEY}" \
  -H "Content-Type: application/json" 2>/dev/null)

if [ "$HTTP_CODE" -eq 200 ]; then
  echo "✅ Connected successfully!"
elif [ "$HTTP_CODE" -eq 401 ]; then
  echo "❌ Authentication failed — check your API key" >&2
  exit 1
elif [ "$HTTP_CODE" -eq 000 ]; then
  echo "❌ Could not reach ${API_URL} — check the URL" >&2
  exit 1
else
  echo "⚠️  Got HTTP $HTTP_CODE — connection may have issues"
fi

# ─── Show Projects ────────────────────────────────────

echo ""
echo "Available projects:"
echo "-------------------"

PROJECTS=$(curl -s "${API_URL}/api/v1/projects" \
  -H "Authorization: Bearer ${API_KEY}" \
  -H "Content-Type: application/json" 2>/dev/null)

if command -v jq &>/dev/null; then
  echo "$PROJECTS" | jq -r '.data[] | "  \(.id)  \(.prefix)-*  \(.name)"' 2>/dev/null || echo "  (no projects found)"
else
  echo "$PROJECTS"
fi

# ─── Select Project ──────────────────────────────────

echo ""
read -rp "Project ID to use (or press Enter to skip): " PROJECT_ID

# ─── Write Config ─────────────────────────────────────

CONFIG_FILE=".baaton"
cat > "$CONFIG_FILE" <<EOF
# Baaton configuration
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
api_url=${API_URL}
api_key=${API_KEY}
EOF

if [ -n "$PROJECT_ID" ]; then
  echo "project_id=${PROJECT_ID}" >> "$CONFIG_FILE"
fi

echo ""
echo "✅ Config saved to ${CONFIG_FILE}"
echo ""
echo "Add .baaton to your .gitignore (contains API key):"
echo '  echo ".baaton" >> .gitignore'
echo ""
echo "Usage:"
echo "  export BAATON_API_KEY=${API_KEY}"
echo "  # or let scripts auto-detect .baaton file"
